openapi: 3.0.0
info:
  title: Manage Latter posts API
  version: 1.0.0
  description: API for managing posts on Latter

servers:
  - url: https://latter-sigma.vercel.app/

paths:
  /api/posts:
    post:
      summary: Create a new post
      operationId: createPost
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                author:
                  type: string
                  example: John Doe
                handle:
                  type: string
                  example: johndoe
                message:
                  type: string
                  example: This is a great post
              required:
                - author
                - message
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: created item ID
                    example: abc
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid author

